services:
  php:
    build: .
    container_name: app-php
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: banco-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
